kind: Service
apiVersion: v1
metadata:
    name: wp-redirect
spec:

    type: ExternalName
    externalName: 192.168.5.102

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wp-redirect-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: wp-redirect
          servicePort: 56395

    host: baharehkaramifar.com
    




